Cerenss/issue6
202303-PRM-TR-FEW/capstone-project-team-5 pull request #11
Opened 2023-07-04 18:44 UTC by cerenss

Added the **"My Learning"** section to the **Home Page.** 

The section currently uses **mock data from the data folder**, as the API data is not yet implemented. 

This commit introduces the **initial structure, layout, and styling** for the "My Learning" section, **ready for integration with the API in future updates.**

2023-07-04 18:54 UTC, cerenss commented
There is nothing displayed in the Netlify preview. I don't know what is the problem.

2023-07-04 19:08 UTC, wasimtayyan commented
> There is nothing displayed in the Netlify preview. I don't know what is the problem.
> 
> ** I need to navigate to _/main/home_ manually. Is it how it supposed to be, or there is something I am missing?

> No there is nothing wrong with manually navigating for now because we will navigate the pages later on by navbar

2023-07-04 19:37 UTC, wasimtayyan requested changes
easy to read code because of good comments but there is a missing dependencies from [package.json] file why !

2023-07-04 19:37 UTC, wasimtayyan commented on app/page.js
> +
you don't need 'use client' & these imports here

2023-07-04 19:37 UTC, wasimtayyan commented on package.json
> -    "tailwindcss": "3.3.2"
why you deleted those ?!

2023-07-04 19:37 UTC, wasimtayyan commented on data/index.html
Are you need this file for the mock API ??

2023-07-04 19:42 UTC, cerenss commented on package.json
> -    "tailwindcss": "3.3.2"
I did not delete any of these by hand, there could be some mistake

2023-07-04 19:43 UTC, cerenss commented on data/index.html
I was checking something, sorry forgot it was there. I will delete it

2023-07-04 19:43 UTC, cerenss commented on app/page.js
> +
Will remove them

2023-07-04 20:05 UTC, vuslatsena commented
It's a clean, well structured code 💕 I agree with Wasim's comments. After editing them, we will check again.

2023-07-05 12:44 UTC, wasimtayyan approved these changes

2023-07-05 15:09 UTC, vuslatsena approved these changes

2023-07-05 15:18 UTC, wasimtayyan reviewed
just some styling changes😅

2023-07-05 15:18 UTC, wasimtayyan commented on app/main/home/page.jsx
> -    <div className="container mx-auto px-4  max-w-screen-xl">
use this class name for styling 
 and make "My Learning"  the same size as "featured courses" You can use this class name: text-3xl font-bold

2023-07-05 19:26 UTC, merged