Issue 16 editing category
202303-PRM-TR-FEW/capstone-project-team-5 pull request #23
Opened 2023-07-10 14:03 UTC by BilalAlmalih

- editing styling 
-adding functionality
-removing my learning (the file is still there I just removed it from home/page )
#16

2023-07-10 14:19 UTC, wasimtayyan requested changes
you did a great job thanks but there is a small issue you repeated the Astronomy category

2023-07-10 14:19 UTC, wasimtayyan commented on components/Categories.jsx
> +
two Astronomy  !!?
you can replace it with 'web development '

2023-07-10 14:36 UTC, BilalAlmalih commented on components/Categories.jsx
> +
i thought we were gonna change them anyway depending on the courses.

2023-07-10 14:55 UTC, wasimtayyan approved these changes

2023-07-11 09:20 UTC, vuslatsena commented
There were conflicts on 2 pages @BilalAlmalih , if you solve them, we will merge. good luck, good work 🙌🏽

2023-07-11 09:23 UTC, vuslatsena requested changes
There were conflicts on 2 pages @BilalAlmalih , if you solve them, we will merge. good luck, good work 🙌🏽

2023-07-11 09:41 UTC, cerenss approved these changes
Note: If we are going to use the new course data on firebase datastore, the category names and amount will have to change.

2023-07-11 12:35 UTC, wasimtayyan approved these changes

2023-07-11 12:35 UTC, merged