Hard coded part of Search Page completed
202303-PRM-TR-FEW/capstone-project-team-5 pull request #28
Opened 2023-07-13 17:16 UTC by Maral-Kepenekli

Completed the hard-coded part of the Search Page as we discussed before. 

Fixes #15

2023-07-14 08:36 UTC, wasimtayyan requested changes
please if you can change this today so we can merge it before sprint meeting

2023-07-14 08:36 UTC, wasimtayyan commented on components/search-page/SearchPage.jsx
> +         </div>
it should be an array that keeps the search keyword and then map that array to display 5 or 6 buttons

2023-07-14 09:36 UTC, wasimtayyan commented
if you can fix this also 
![image](https://github.com/202303-PRM-TR-FEW/capstone-project-team-5/assets/127048388/00f5c88e-8437-47e3-b28f-717f24a3d83c)
try to centre  content in the screen

2023-07-14 13:37 UTC, cerenss requested changes

2023-07-14 13:37 UTC, cerenss commented on components/search-page/SearchPage.jsx
> +      setIntermediate(!intermedite);
**!intermediate** --> because of the typo the checkbox of intermediate level is not working

2023-07-14 13:37 UTC, cerenss commented on components/search-page/SearchPage.jsx
> +                  </div>
Instead of creating a code block for each level, there should be one code block that will create reusable checkbox component. You can either create it as a component in another file or you can write the function here  and loop through the array of levels that will come from datastore.

example code:

**// Checkbox Component**

```
function Checkbox({ id, label, checked, onChange }) {
  return (
    <div>
      <CheckIcon
        className={`w-5 h-5 absolute ${checked ? 'opacity-100' : 'opacity-0'}`}
      />
      <input
        type="checkbox"
        id={id}
        value={id}
        className="w-5 h-5 appearance-none border-2 rounded-lg border-gray-300 relative"
        onChange={onChange}
        checked={checked}
      />
      <label htmlFor={id}>{label}</label>
    </div>
  );
}
```


**// Search Page**

```
function App() {
  const [levels, setLevels] = useState([
    { id: 'beginner', label: 'Beginner', checked: false },
    { id: 'intermediate', label: 'Intermediate', checked: false },
    { id: 'professional', label: 'Professional', checked: false }
  ]);
  
  //Later, we can change this array with the data coming from firebase datastore.
  

  function handleLevelInputChange(index) {
    setLevels(prevLevels => {
      const newLevels = [...prevLevels];
      newLevels[index].checked = !newLevels[index].checked;
      return newLevels;
    });
  }

  return (
    <div>
      {levels.map((level, index) => (
        <Checkbox
          key={level.id}
          id={level.id}
          label={level.label}
          checked={level.checked}
          onChange={() => handleLevelInputChange(index)}
        />
      ))}
    </div>
  );
}

```

2023-07-14 13:37 UTC, cerenss commented on components/search-page/SearchPage.jsx
> +   const [design, setDesign] = useState(false);
Same principle with my **Level Checkbox** review can be applied to the Categories Checkbox component.

2023-07-14 15:34 UTC, Maral-Kepenekli commented on components/search-page/SearchPage.jsx
> +      setIntermediate(!intermedite);
solved the typo! Thank you for your review

2023-07-16 14:34 UTC, wasimtayyan approved these changes
thank you for the changes you made. now the code is readable and more organized.
  I have one  question that I couldn't understand how are we gonna access the categories & ratings & levels values inside the search page component !!

2023-07-16 18:15 UTC, Maral-Kepenekli commented
I asked this question before :) I suggested to render them in Recommended Part, if you are agree.... We can discuss this issue

2023-07-17 17:38 UTC, cerenss commented
Thank you Maral for your valuable work! I don't think you fetched the data from firestore, that is why we don't see any result on the page. I don't see any problem right now. I think this should do it :)

2023-07-17 17:38 UTC, merged